---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weather-api
spec:
  interval: 5m0s
  url: https://github.com/ryansheppard/weather-api
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weather-api
spec:
  interval: 5m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: weather-api
  path: "./deployments"
  prune: true
  timeout: 1m
