[package]
name = "weathe_rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = { version = "0.12.24", default-features = false, features = [
  "rustls-tls",
  "json",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5.7"
axum = { version = "0.8.7", default-features = false, features = [
  "json",
  "query",
] }
anyhow = "1.0.100"
futures-util = "0.3.34"

worker = { version = "0.8", features = ['http', 'axum'] }
tower-service = "0.3.3"
