---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  labels:
    app: weather
spec:
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: registry.digitalocean.com/ryansheppard/weather:dc7e9dd
          imagePullPolicy: Always
          command:
            - "/weather"
          ports:
            - containerPort: 1323
              name: http
            - containerPort: 1324
              name: prometheus
          env:
            - name: NWS_BASE_URL
              value: "https://api.weather.gov"
            - name: PURPLE_AIR_BASE_URL
              value: "https://api.purpleair.com/v1"
            - name: REDIS_ADDR
              value: redis.default.svc.cluster.local:6379
          envFrom:
            - secretRef:
                name: weather
